### DISCUSSION TITLE
applying language hfs-lang-rs.json

### DISCUSSION THREAD

**Discussion by gogi100** [rejetto/hfs#127] [Q&A]
i created language hfs-lang-rs.json but i don't know how i used them
[hfs-lang-sr.zip](https://github.com/rejetto/hfs/files/10880304/hfs-lang-sr.zip)

**Comment by rejetto** [comment]
it's serbian, right?
i can include it, no problem

**Reply by gogi100** [reply]
yes, serbian language. one more question, how i can change layout,theme? how i set my custom login page?

**Reply by rejetto** [reply]
you can add/change the style (CSS).
use the "custom header" function (in configuration) and inserting your code like this
<style>
#root { background-color: red }
</style>

**Reply by gogi100** [reply]
custom login page no default first page when i typed address of my hfs

**Reply by gogi100** [reply]
add some picture?

**Reply by rejetto** [reply]
login page has style too.
your browser has tools to inspect names, for example login is: .dialog-login
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1367199/222684833-be0cbe74-3857-4fbb-980a-989bc0f64f9d.png">

pictures is also possible with style. You can share the pictures in a hidden folder (VFS) or if it's few kb you can have it embedded inside the style itself.

**Reply by gogi100** [reply]
where is hidden folder vfs. can you give me some instruction how replace first hfs page with my custom login page?

**Reply by rejetto** [reply]
you can create your own hidden folder in vfs.
hidden = you remove permissions to see the folder.

**Comment by gogi100** [comment]
I managed to load the custom login what i want, but i click on button i receive message not found, what i do that i can logon on folder. the code on page is in attachemtn
![login](https://user-images.githubusercontent.com/21057856/222703939-6aeec29a-22a7-408d-9c77-986e2de00cc7.jpg)

**Reply by rejetto** [reply]
you cannot use stuff of HFS 2.3 on HFS 3.
they are completely different.

HFS 3 system allows less customization but it's harder to break.

**Comment by gogi100** [comment]
thanks for uploading serbian language, but i dont know how applying serbian language, i tryed from admin panel, but nothing

**Reply by rejetto** [reply]
go here and tell me what it says
https://manytools.org/http-html-text/browser-language/

i'm italian and to me it says
```
Your browser's Accept-Language header:
it-IT,it;q=0.9,en-GB;q=0.8,en-US;q=0.7,en;q=0.6
```

**Reply by gogi100** [reply]
Your browser's Accept-Language header:
en-US,en;q=0.9,sr;q=0.8

**Reply by rejetto** [reply]
i installed your lang file
<img width="207" alt="image" src="https://user-images.githubusercontent.com/1367199/222747189-e699a42a-3860-4223-8112-736ffb2cdc62.png">

then configured my chrome to use serbian as first language
<img width="206" alt="image" src="https://user-images.githubusercontent.com/1367199/222747127-44d029bb-003f-472b-8d24-c2c6062e986e.png">

and now my hfs is correctly translated
<img width="196" alt="image" src="https://user-images.githubusercontent.com/1367199/222747330-e803c6be-1159-485b-a1f4-0a867b9fd43f.png">


i don't know what's wrong on your side, check all these steps

**Reply by gogi100** [reply]
I cannot install language in admin panel. Everytime it shows loaded but language does not displays

**Reply by rejetto** [reply]
show some screenshot or it's impossible to help you

**Reply by gogi100** [reply]
screen shoots from admin panel
![1](https://user-images.githubusercontent.com/21057856/222779322-eb86e467-6692-4ee4-be32-9c0dd2a10725.jpg)
![2](https://user-images.githubusercontent.com/21057856/222779330-7ad85c12-795d-43c7-9a35-5728dd8651b6.jpg)
![3](https://user-images.githubusercontent.com/21057856/222779331-a15c3069-3d22-457c-b6dd-44f48cb81bef.jpg)

**Comment by rejetto** [comment]
i'm not sure why the "add" is not working for you.
You can do it manually: just copy the file in the same folder of file config.yaml

**Reply by gogi100** [reply]
Language file json is displayed in folder where hfs but he does exists in sdmin panel

**Comment by rejetto** [comment]
can you show me the console output when you run HFS ?

**Reply by gogi100** [reply]
console output is
![4](https://user-images.githubusercontent.com/21057856/222887541-7c57de29-9e56-4f4e-8c38-6e6661528fce.jpg)

**Reply by gogi100** [reply]
my yaml file is
```
accounts:
  admin:
    redirect: /deljeni
    admin: true
    srp: ...
  test:
    redirect: /deljeni
    srp: ...
vfs:
  children:
    - source: C:\hfs-windows\RAWR-Template-0.1.3\template
      can_see: false
      can_read: "*"
      can_upload: false
      can_delete: false
    - source: index.html
      can_see: false
      can_read: "*"
    - source: C:\hfs-windows\images\favicon.ico
      can_see: "*"
      can_read: "*"
    - source: C:\deljeni
      can_see:
        - admin
        - test
      can_read:
        - admin
        - test
      can_upload:
        - admin
        - test
      can_delete:
        - admin
  can_see:
    - admin
  can_read:
    - admin
  can_upload:
    - admin
  can_delete:
    - admin
allowed_referer: "-"
enable_plugins:
   - antibrute
   - vhosting
   - redirect-root
   - max-downloads-ip
open_browser_at_start: false
delete_unfinished_uploads_after: 300
dont_overwrite_uploading: true
custom_header: dr
plugins_config:
  redirect-root:
    url: ""
favicon: images\favicon.ico
title: DR
```
