### DISCUSSION TITLE
any plans for docker and docker compose support?

### DISCUSSION THREAD

**Discussion by aniel300** [rejetto/hfs#551] [Ideas]
any plans to support docker and docker compose support?

**Comment by rejetto** [comment]
i'm not sure what is needed for docker as i'm no docker user myself, but i tried to write a few instructions here https://github.com/rejetto/hfs/wiki/Docker/
feel free to edit the page if you have any contribution.
i know @damienzonly is working on something.

**Comment by aniel300** [comment]
perfect can't wait to test it out

**Comment by Jarusz** [comment]
Is there any chance for a docker-compose instructions? something similar what linuxserver gives, for example https://hub.docker.com/r/linuxserver/plex where i could just specify paths to the folders which i want to share etc, that would be such a great thing, for those of us who arent that great with docker

**Reply by aniel300** [reply]
am in the same boat. @damienzonly can u help on this?

**Comment by aniel300** [comment]
this is what https://www.composerize.com/ gives me but am not sure if this would work
![image](https://github.com/rejetto/hfs/assets/7571729/fc860d40-58ed-465a-bd76-89680e3428ec)

**Comment by aniel300** [comment]
i was able to get it up and running with this but now am unable to ssh into the container to run the admin command. here are some screenshots

![image](https://github.com/rejetto/hfs/assets/7571729/6083622e-9e7f-40e5-b8a0-b274ff4c4498)
 
![image](https://github.com/rejetto/hfs/assets/7571729/c8b319bf-4de9-4c4c-a8dc-6e06e22ce457)

**Comment by damienzonly** [comment]
yep, i'm working on having docker support, the first step is to have a working dockerfile, then i'll see what env variables i may support, for example to let you create the first admin user, configure the http/https port, etc.. i'll keep you updated

**Reply by aniel300** [reply]
> yep, i'm working on having docker support, the first step is to have a working dockerfile, then i'll see what env variables i may support, for example to let you create the first admin user, configure the http/https port, etc.. i'll keep you updated

that is awesome. am not worried about https since i have my own reverse proxy up and running which takes care of https and ssl certs. but yes please do keep me updated 🙏

**Reply by damienzonly** [reply]
Hi @aniel300, thanks for the interest. I've been working a little bit on the docker support and for now there's only one image `rejetto/hfs:0.52.7`, not well documented, it should work fine and also allowing you to configure stuff via env ([see this file for envs reference](https://github.com/damienzonly/hfs/blob/docker/docker/entrypoint.sh).
There are other priorities and discussions to make in order to deliver HFS in docker, i'll keep you updated, in the meantime you can try the image out and let me know if you have any issues

**Reply by aniel300** [reply]
thank you for getting back to me and can't wait to test this out and report back. also can u share how ur compose file is looking so i can use it as reference?

**Comment by damienzonly** [comment]
@aniel300 @Jarusz hi guys, the official docker images are out https://hub.docker.com/r/rejetto/hfs, i also provided the docker run command and an example of compose file. let me know if it works. Feel free to open issues here https://github.com/damienzonly/hfs-docker/issues

**Reply by aniel300** [reply]
cant wait to try it out, thanks.

**Reply by aniel300** [reply]
@damienzonly am getting this error
![image](https://github.com/user-attachments/assets/8082bc52-e9f5-4a71-a9df-b07571ee7b3d)

**Reply by damienzonly** [reply]
are you mounting a volume to /app? maybe if you provide the compose file you're using it would help me understand better

**Reply by aniel300** [reply]
here is my compose:

hfs:
    image: rejetto/hfs:v0.54.0-alpha2
    container_name: hfs
    volumes:
      - $PERSIST/hfs:/app # for hfs conf persistence
      - /data:/app/myDisk # for your files
      # don't forget to share volumes to access certificate files
    environment:
      - HFS_PORT=8080 # default is 80
      - HFS_CREATE_ADMIN=xxx # will create the admin user with password "password123" \
    ports:
      - 8080:8080

**Reply by damienzonly** [reply]
right, i fixed the documentation with the right compose, basically there was a wrong cwd documented. try mounting `$persist` into `/home/hfs/.hfs `instead of `/app`

**Reply by aniel300** [reply]
am getting this error and cant reach the webui

04:07:10 HFS ~ HTTP File Server
04:07:10 © Massimo Melina <a@rejetto.com> - License https://www.gnu.org/licenses/gpl-3.0.txt
04:07:10 started 9/26/2024, 4:07:10 AM 
04:07:10 version 0.53.0
04:07:10 build 2024-09-25T22:29:20.090Z
04:07:10 cwd /home/hfs/.hfs
04:07:10 app /app
04:07:10 node v18.5.0
04:07:10 platform linux x64
04:07:10 pid 1
04:07:10 config config.yaml
04:07:10 No config file, using defaults
04:07:11 HINT: type "help" for help
04:07:11 cannot create debug.log
04:07:11 account admin created
04:07:11 cannot create folder for logs/access.log
04:07:11 cannot create folder for logs/access-error.log
04:07:11 uncaught: [Error: EACCES: permission denied, open 'data.kv'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'data.kv'
}
04:07:11 uncaught: [Error: EACCES: permission denied, open 'ips.kv'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'ips.kv'
}
04:07:11 Failed at saving config file, please ensure it is writable. Error: EACCES: permission denied, open 'config.yaml'
04:08:52 HFS ~ HTTP File Server
04:08:52 © Massimo Melina <a@rejetto.com> - License https://www.gnu.org/licenses/gpl-3.0.txt
04:08:52 started 9/26/2024, 4:08:52 AM 
04:08:52 version 0.53.0
04:08:52 build 2024-09-25T22:29:20.090Z
04:08:52 cwd /home/hfs/.hfs
04:08:52 app /app
04:08:52 node v18.5.0
04:08:52 platform linux x64
04:08:52 pid 1
04:08:52 config config.yaml
04:08:52 No config file, using defaults
04:08:53 HINT: type "help" for help
04:08:53 cannot create debug.log
04:08:53 account admin created
04:08:53 cannot create folder for logs/access.log
04:08:53 cannot create folder for logs/access-error.log
04:08:53 uncaught: [Error: EACCES: permission denied, open 'data.kv'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'data.kv'
}
04:08:53 uncaught: [Error: EACCES: permission denied, open 'ips.kv'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'ips.kv'
}
04:08:53 Failed at saving config file, please ensure it is writable. Error: EACCES: permission denied, open 'config.yaml'

**Reply by damienzonly** [reply]
it doesn't seem a permission error of the hfs user inside the container, maybe you mounted the /home/hfs/.hfs directory outstide in a folder where there is no write permission i guess

**Reply by aniel300** [reply]
the container is using root for it folder creation, i wish it would use my user and maybe that is the issue but idk

**Reply by damienzonly** [reply]
you mean that when perfoming the docker run command (or compose up) the mounted folder on the host is created with root permissions?

in that case it may happen if you use sudo before docker command. try not to use sudo. 

i would  tell you to try with chmod after creation (or the equivalent in windows) but it would be better if you use the right unprivileged user at the beginning

**Reply by aniel300** [reply]
correct however this is dependent on the container as 95 of my containers uses my user for the folder creation. here is a screenshot of how it looks
![image](https://github.com/user-attachments/assets/ebe53043-2129-4fb0-89e5-1b7ff958f254)

**Reply by damienzonly** [reply]
i need some additional info about the way you are running hfs in docker. while testing this system i always used an unprivileged user, still now i'm re-doing the tests and docker never creates a directory on the host owned by root.
what's the command you use to run the container?
do you use compose?
which version of docker do you have?
i have no idea why this is happening to you, the more info you provide, the more easy will be the troubleshooting for me

**Reply by aniel300** [reply]
of course I will try rpovide any info u mi0ght need

here is my docker version and yes am using docker compose. here is also my docker compose.
`Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:19 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

  hfs:
    image: rejetto/hfs:v0.53.0
    container_name: hfs
    volumes:
      - $PERSIST/hfs:/home/hfs/.hfs # for hfs conf persistence
      - /data:/app/myDisk # for your files
      # don't forget to share volumes to access certificate files
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIME_ZONE    
      - HFS_PORT=8080 # default is 80
      - HFS_CREATE_ADMIN=xxx # will create the admin user with password "password123" \
    ports:
      - 8080:8080

**Reply by damienzonly** [reply]
i'm not sure what you're trying to accomplish by providing puid and pgid, try removing them and see if the error persists. i don't know the purpose of those variables, anyway it may be messing with permissions. fyi the official docker image uses the "hfs" user created on puropose to execute hfs without root permissions. let me know what was your objective

**Reply by aniel300** [reply]
there is no objective on my part, i included the ppgid as a ts. it didn't work without it. idk what else to do

**Comment by bmartino1** [comment]
Hi Rejetto, Long time no see. I will take a crack at it.

atm i will be building a docker file in the github and make a docker iamge...


here is an example of the docker file:


```
# Use the Debian-based GUI image for VNC support
FROM jlesage/baseimage-gui:debian-12-v4.6.4 AS base

# Set environment variables
ENV NODE_VERSION=18

# Update packages and install prerequisites
RUN apt-get update && \
    apt-get install -y curl gnupg2 lsb-release software-properties-common wget && \
    rm -rf /var/lib/apt/lists/*

# Install Node.js version 18
RUN curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

# Create a new user to run the HFS application
RUN addgroup --system hfs && \
    adduser --system --ingroup hfs hfs

# Switch to non-root user
USER hfs

# Set up HFS
RUN npm install -g npx

# Run HFS using npx on container start
CMD ["npx", "hfs@latest"]

# Expose port for HFS access
EXPOSE 8080

# Finalize the VNC configuration (adding a browser)
USER root
RUN apt-get update && \
    apt-get install -y firefox-esr && \
    rm -rf /var/lib/apt/lists/*

# Set default environment variables for VNC
ENV APP_NAME="HFS with VNC"
ENV RUN_AS_USER="hfs"

# Start HFS with VNC viewer enabled
ENTRYPOINT ["/init"]
```

the plan is a docker with vnc / firefox to view the admin interface.

Volumes
the a docker mount for data /data
and a dokcer mount for the .vfs hfs config files.. 

I want a docker with a vnc web view:
FROM jlesage/baseimage-gui:debian-12-v4.6.4 AS download

So lets use debain. I will need a web browser to access the application in it.
I will need to pull form these site too:
https://docs.docker.com/guides/nodejs/containerize/
https://github.com/nodejs/docker-node
Form The Hub: https://hub.docker.com/_/node/tags

It will take me a while to get to completion. I will be useing  your other setup per the github... but here is a sample...
https://github.com/bmartino1/Docker_VNC_RejetoHFS

**Reply by damienzonly** [reply]
hi @bmartino1, we've already deployed official hfs images on rejetto's docker registry.
did you check them out?
the repository for images build process is at https://github.com/damienzonly/hfs-docker

**Reply by rejetto** [reply]
hi @bmartino1, happy to see you again :)

**Comment by bmartino1** [comment]
Thank you for this. I didn't know if it existed. I will check that out now.

**Comment by bmartino1** [comment]
Hi,

Just wanted to let you know that I will attempt to expand your audience on
another platform.

https://github.com/bmartino1/unraid-docker-templates

I wanted to give Thanks to Both Rejetto and Thanks to damienzonly for
starting me on the right path:

I originally attempted to fork damienzonly Repo. Decided to clone
separate due to some core changes needed specficaly for unriad.
that repo can be found here.
https://github.com/bmartino1/hfs-docker

With a working docker compose on unraid Linux Slackware Docker System. I
have successfully added your app to a Unraid Point and Click Appstore.
https://github.com/bmartino1/unraid-docker-templates

[image: image.png]

Which will allow unraids users to use your application on the Unraid
Platform in docker format.

[image: image.png]

I will attempt to follow and maintain this to your standards. Thank you
both!

**Comment by rejetto** [comment]
I never used unraid, but this sounds like a cool project :)
if you need an updated HFS icon, here it is
[hfs-logo-icon.svg.zip](https://github.com/user-attachments/files/17612261/hfs-logo-icon.svg.zip)

**Comment by bmartino1** [comment]
Awesome, thanks!

I will update that Unraid use png images:
https://raw.githubusercontent.com/bmartino1/unraid-docker-templates/refs/heads/main/images/rejettohfs.png

**Comment by patschi** [comment]
FWIW, I have just made my own docker-build project for HFS, which is completely differing from the current available repo(s): https://github.com/patschi/hfs-docker. One reason being that I have not found latest 0.54.0 in the other docker project and found it too 'bloaty' even with Alpine.

The major difference is, that it uses the pre-compiled binaries from this repo. Hence, building containers is way less sensitive to errors and quicker compared to compiling.

It's completely automated for all HFS releases (via API and includes prereleases/beta/RCs; without any requirement for user intervention) and uses the `distroless` container base image by Google, which is way smaller, secure and contains no extra 'junk' as others even compared to `alpine`.

I have let it built the [last 20 releases](https://github.com/patschi/hfs-docker/pkgs/container/hfs-docker/versions), should anyone ever want to pick a older release. The latest stable release in this main hfs-repo is always automatically tagged as `latest`.

**Reply by aniel300** [reply]
will take a look, thanks

**Reply by harrischrisa** [reply]
I am using TrueNAS Community for data backup. I would like to see, copy share files. I am using HFS on my Windows PC successfully. I would like to use HFS on my TrueNAS box using Dockge. While I have a very limited knowledge of TruesNAS and Linux I do have the NAS working. It is running Immich and Resilio Sync.

I have 2 disk storage. On is a SSD (/mnt/ssd/) for mainly app data and databases and a HDD (/mnt/hdd/)  for the large datasets of files and photographs.

I have tried to setup HFS. With out success. Details of my setup are below.

Can anyone assist me to get HFS working on my TrueNAS box?

Thanks 
Chris

Here is the compose.yaml I used in dockge

version: '3'

services:
  hfs:
    image: rejetto/hfs:v0.53.0
    volumes:
      - ./hfsconf:/home/hfs/.hfs # for hfs conf persistence
      # don't forget to share volumes to access certificate files
    environment:
      - HFS_PORT=8080 # default is 80
      - HFS_CREATE_ADMIN=hfs_852 # will create the admin user with password "hfs_852" \
    ports:
	- 8080:8080




This runs but I cannot connect to the local site. There seems to be a series of permission errors and file storage problems.

When starting I get this message
WARN[0000] /mnt/ssd/docker/stacks/hfs/compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✔ Container hfs-hfs-1  Started 

The dockge terminal shows the following

hfs-1  | 01:22:24 started 7/20/2025, 1:22:24 AM 
hfs-1  | 01:22:24 version 0.53.0
hfs-1  | 01:22:24 build 2024-09-25T22:29:20.090Z
hfs-1  | 01:22:24 cwd /home/hfs/.hfs
hfs-1  | 01:22:24 app /app
hfs-1  | 01:22:24 node v18.5.0
hfs-1  | 01:22:24 platform linux x64
hfs-1  | 01:22:24 pid 1
hfs-1  | 01:22:24 config config.yaml
hfs-1  | 01:22:24 No config file, using defaults
hfs-1  | 01:22:25 HINT: type "help" for help
hfs-1  | 01:22:25 cannot create debug.log
hfs-1  | 01:22:25 account admin created
hfs-1  | 01:22:25 cannot create folder for logs/access.log
hfs-1  | 01:22:25 cannot create folder for logs/access-error.log
hfs-1  | 01:22:25 uncaught: [Error: EACCES: permission denied, open 'data.kv'] {
hfs-1  |   errno: -13,
hfs-1  |   code: 'EACCES',
hfs-1  |   syscall: 'open',
hfs-1  |   path: 'data.kv'
hfs-1  | }
hfs-1  | 01:22:25 uncaught: [Error: EACCES: permission denied, open 'ips.kv'] {
hfs-1  |   errno: -13,
hfs-1  |   code: 'EACCES',
hfs-1  |   syscall: 'open',
hfs-1  |   path: 'ips.kv'
hfs-1  | }
hfs-1  | 01:22:25 Failed at saving config file, please ensure it is writable. Error: EACCES: permission denied, open 'config.yaml'

**Reply by rejetto** [reply]
@harrischrisa i don't know much of this, but i can see that HFS is failing at writing in the folder that you set for configuration storage (hfsconf). It tries but the system denies permission.

**Reply by bmartino1** [reply]
I don't know dockerage. and at one time i did make a compose for this..

yaml Compse:
```version: "3.8"

services:
  rejettohfs3:
    image: rejetto/hfs:latest
    container_name: rejettohfs3
    hostname: HFS3
    network_mode: "br0"  # macvlan docker network on Unraid; make sure you assign a static IP to this docker!
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HFS_CREATE_ADMIN=your_secure_password_here       # Replace with your HFS admin password
      - HFS_LOG_ROTATION=weekly
      - HFS_FORCE_HTTPS=true
      - HFS_ADMIN_NET=192.168.1.0/24                     # Adjust to your local network subnet
      - PUID=0
      - PGID=0
      - HFS_HTTPS_PORT=443
      - HFS_PORT=80
      - HFS_CERT=/app/certs/cert.pem
      - HFS_PRIVATE_KEY=/app/certs/privkey.key
      - HFS_ERROR_LOG=/app/logs/error.log
      - HFS_LOG=/app/logs/access.log
      - HFS_VFS={"source": "/app/myDisk"}
    volumes:
      - /mnt/user/appdata/rejettohfs3/config:/home/hfs/.hfs
      - /mnt/user/appdata/rejettohfs3/certificate:/app/certs
      - /mnt/user/appdata/rejettohfs3/logs:/app/logs
      - /mnt/user/:/app/myDisk #path shared as home folder for HFS
    restart: unless-stopped
```
--unraid adational guide:
https://raw.githubusercontent.com/bmartino1/unraid-docker-templates/refs/heads/main/Guides/Quick%20Start%20Guide%20For%20Rejeto%20HFS.txt

truenas uses helm docker and while possible to run not easily setup for a template config in how truenas / charts are made.

for unriad I was able to add this to Unraid CA by making a xml uraid temaplte and worked to iron out some inconsistency.
https://github.com/bmartino1/unraid-docker-templates/blob/main/rejettohfs3.xml

there a inhert issues trying to run dockers with truenas scale and how scale runs dockers.
https://www.youtube.com/watch?v=is82nyAfWq4

**Reply by bmartino1** [reply]
I do not recommend running dockers native on turenas. I would highly recommend a debian VM and running docker from in that VM...

However, You can use this with helm install via TrueNAS CLI or in a custom chart:

yaml code 
```
image:
  repository: rejetto/hfs
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "rejettohfs3"
fullnameOverride: "rejettohfs3"

service:
  type: ClusterIP
  ports:
    http:
      port: 80
    https:
      port: 443

hostNetwork: true  # Needed if you want to bind directly to host's IP (mimics `network_mode: br0`)
dnsPolicy: ClusterFirstWithHostNet

persistence:
  config:
    enabled: true
    mountPath: /home/hfs/.hfs
    hostPath: /mnt/user/appdata/rejettohfs3/config
  certs:
    enabled: true
    mountPath: /app/certs
    hostPath: /mnt/user/appdata/rejettohfs3/certificate
  logs:
    enabled: true
    mountPath: /app/logs
    hostPath: /mnt/user/appdata/rejettohfs3/logs
  shared:
    enabled: true
    mountPath: /app/myDisk
    hostPath: /mnt/user/

env:
  HFS_CREATE_ADMIN: "your_secure_password_here"    # ⚠️ Set your admin password
  HFS_LOG_ROTATION: "weekly"
  HFS_FORCE_HTTPS: "true"
  HFS_ADMIN_NET: "192.168.1.0/24"
  PUID: "0"
  PGID: "0"
  HFS_HTTPS_PORT: "443"
  HFS_PORT: "80"
  HFS_CERT: "/app/certs/cert.pem"
  HFS_PRIVATE_KEY: "/app/certs/privkey.key"
  HFS_ERROR_LOG: "/app/logs/error.log"
  HFS_LOG: "/app/logs/access.log"
  HFS_VFS: '{"source": "/app/myDisk"}'

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

```

🗂 File Structure for a Minimal Helm Chart

```
rejettohfs3/
├── Chart.yaml
├── values.yaml           # (from above)
└── templates/
    ├── deployment.yaml
    ├── service.yaml
```

This will require making a few files for truenas to interpret...

Minimal Chart.yaml

yaml
```apiVersion: v2
name: rejettohfs3
description: Rejetto HFS3 HTTP File Server
type: application
version: 0.1.0
appVersion: "3"
```

templates/deployment.yaml
yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rejettohfs3.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rejettohfs3.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rejettohfs3.name" . }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: hfs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: certs
              mountPath: {{ .Values.persistence.certs.mountPath }}
            - name: logs
              mountPath: {{ .Values.persistence.logs.mountPath }}
            - name: shared
              mountPath: {{ .Values.persistence.shared.mountPath }}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.persistence.config.hostPath }}
        - name: certs
          hostPath:
            path: {{ .Values.persistence.certs.hostPath }}
        - name: logs
          hostPath:
            path: {{ .Values.persistence.logs.hostPath }}
        - name: shared
          hostPath:
            path: {{ .Values.persistence.shared.hostPath }}
```

templates/service.yaml
yaml
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rejettohfs3.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rejettohfs3.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: 80
    - name: https
      port: {{ .Values.service.ports.https.port }}
      targetPort: 443
```

How to Deploying on TrueNAS SCALE:
Zip this Helm chart (rejettohfs3/) into a tar.gz or deploy it via TrueNAS SCALE “Custom App” GUI using:

values.yaml

Volume mounts pointing to your hostPath (in /mnt/user/)
*A default path app location reusing data from unraid...

Optionally import this as part of your own catalog... making a charts github and adding a repo...

I'm sorry your on your own form this point. I left Truenas many moons ago and HIGHLY DON"T RECOMMEND THEM!!!
-At one time i was a beta dev for them and left after being shut out and they lost the comunity 3 time between builds They can't maintain what they have... With the lost of k3/k8 and gluster FS truenas has yet to fix nor pickup the ball and have reverse course again. I would not run any sensitive nas or backup on that platform!!!
If running truenas look into the paid hexos that use a better configure and fixed on the truenase paltform...

I'd point you at and advised you use Debian Open Media Vault... Free works and is better at runnign docker via compose/protainer etc...
