### DISCUSSION TITLE
Code layout for masks

### DISCUSSION THREAD

**Discussion by VegethB** [rejetto/hfs#91] [Q&A] [answered]
If I understand correctly, with masks I can do advanced things like:
```
Uploads/Folder1
Uploads/Folder2
Uploads/
```
Where is it:
 Folder1 is visible only to User1;
 Folder2 is visible only to User2;
 Uploads is visible to everyone BUT only User1 and User2 also see the corresponding folders mentioned above.

The problem is that I tried to write a similar mask and it doesn't get read to me. It fails on ':'.
I used as a basis the mask that is written [here](https://github.com/rejetto/hfs#readme): 

![image](https://user-images.githubusercontent.com/17975351/213249018-ca3a4b3d-7aab-4d77-a35c-5d512eefc536.png)

<details>
 <summary>What i trt:</summary>

```
"Folder1": 
  can_read: [ User1, User1_1, User1_2 ]
  can_see: [ User1, User1_1, User1_2 ]
  can_upload: [ User1, User1_1, User1_2 ]
"Folder2":
  can_read: [ User2, User2_1, User2_2 ]
  can_see: [ User2, User2_1, User2_2 ]
  can_upload: [ User2, User2_1, User2_2 ]
```
or

```
"Folder1": 
  can_read: User1, User1_1, User1_2
  can_see: User1, User1_1, User1_2
  can_upload: User1, User1_1, User1_2
"Folder2":
  can_read: User2, User2_1, User2_2
  can_see: User2, User2_1, User2_2
  can_upload: User2, User2_1, User2_2

```
 or

```
  "Uploads/Folder1":
    can_read:
      - User1
      - User1_1
      - User1_2
    can_see:
      - User1
      - User1_1
      - User1_2
    can_upload:
      - User1
      - User1_1
      - User1_2
  "Uploads/Folder2":
    can_read:
      - User2
      - User2_1
      - User2_2
    can_see:
      - User2
      - User2_1
      - User2_2
    can_upload:
      - User2
      - User2_1
      - User2_2

```

or inside config.yaml

```
masks:
  Uploads/Folder1:
    can_read:
      - User1
      - User1_1
      - User1_2
    can_see:
      - User1
      - User1_1
      - User1_2
    can_upload:
      - User1
      - User1_1
      - User1_2
  Uploads/Folder2:
    can_read:
      - User2
      - User2_1
      - User2_2
    can_see:
      - User2
      - User2_1
      - User2_2
    can_upload:
      - User2
      - User2_1
      - User2_2
      - 
```

</details>

-----------------------------------------------

The result would be that "User2_1" when he opens the Uploads folder on HFS he sees the contents of all Uploads except Folder1 (which with the mask has been set as visible only to user1).

<details>
 <summary>Instead I get stopped first by these errors:</summary>

![Immagine 2023-01-18 173344](https://user-images.githubusercontent.com/17975351/213243064-03f3404d-b6d5-4a1b-9d8e-7cf7d89f206f.png)
![Immagine 2023-01-18 173516](https://user-images.githubusercontent.com/17975351/213243093-3a90c5f2-3482-4d09-af67-fae247503eef.png)

</details>

[VideoExplain](https://mega.nz/file/gwlDFaaR#rGc3oQbbXAZS8btv8a0KXSbh6x-Nk5AJgjGRKvprbPE): https://mega.nz/file/gwlDFaaR#rGc3oQbbXAZS8btv8a0KXSbh6x-Nk5AJgjGRKvprbPE

**Comment by rejetto** [comment]
well, that syntax you use (yaml) works in the config.yaml file
That field in the GUI is using a different format (json), and I see it can be very confusing.
I had json format in the box just because it was quick and free.
It's just a temporary thing, as a real masks editor is not easy and quick to make.
As a small improvement I could see to make it accept also the yaml syntax.

That been said, my suggestion is to use masks only when it is easier to get what you want.
I suspect you can get what you want without: just add folder1/2 under "uploads" folder, and you will be able to configure permissions easily.

Let me know if you don't get what you want. I want to be sure that these features nail the needs of users. If you feel like it, we can have a call and talk (in italian), like on telegram or something.

**Reply by rejetto** [reply]
in case it was not clear, you can still use that syntax if you edit config.yaml

**Reply by VegethB** [reply]
> just add folder1/2 under "uploads" folder, and you will be able to configure permissions easily.

I haven't tried it because the "folder1/2" folders are inside Uploads and therefore I thought that whoever has access to Uploads still sees Folder1 and Folder2 in the list but then cannot access them if they click on them.
![image](https://user-images.githubusercontent.com/17975351/213259588-f983311b-1c5c-48b1-be2d-f9e95b7012dc.png)


As I read in the Readme, in the masks and in the VFS, "can_see" can also be used. This allowed the folder to be completely hidden from everyone except the users I gave permission to see it (if I understood correctly).
––Now I try to add the two folders and set the permissions.––
  Interesting, Folder1 is now duplicated in the view... (screen above)

> in case it was not clear, you can still use that syntax if you edit config.yaml

it was the last test I did,
Put it like this in the config.yaml:

```
masks:
  Uploads/Folder1:
    can_read:
      - User1
    can_see:
      - User1
    can_upload:
      - User1
  Uploads/Folder2:
    can_read:
      - User2
    can_see:
      - User2
    can_upload:
      - User2
```

But it did not work.
When I logged in with User2, I both saw the "Folder1" folder and its contents (which in theory were only meant to be seen by User1).
And this could be that I really don't quite understand what masks actually do.

> Let me know if you don't get what you want. I want to be sure that these features nail the needs of users. If you feel like it, we can have a call and talk (in italian), like on telegram or something.

Va bene anche discord ( ᲼᲼᲼᲼᲼᲼᲼᲼᲼᲼᲼᲼᲼᲼#2854 )
