### ISSUE TITLE
Admin Panel not open on linuxmint

### ISSUE THREAD

**Issue by Akai-Abd** [rejetto/hfs#775]
root@akai:~# npx hfs
04:50:03 HFS ~ HTTP File Server
04:50:03 © Massimo Melina <a@rejetto.com> - License https://www.gnu.org/licenses/gpl-3.0.txt
04:50:03 started 10/15/2024, 4:50:03 AM 
04:50:03 version 0.53.1
04:50:03 build 2024-09-28T16:00:41.759Z
04:50:03 cwd /root/.hfs
04:50:03 app /root/.npm/_npx/d99544b1c5641eb5/node_modules/hfs
04:50:03 node v18.19.1
04:50:03 platform linux x64
04:50:03 pid 75253
04:50:03 config config.yaml
04:50:03 HINT: type "help" for help
04:50:04 http serving on any network : 80
04:50:04 serving on http://192.168.1.10
04:50:05 loading plugin antibrute

**Comment by rejetto** [comment]
i can't install linux mint to make a test, and this is too little information to work on.
you say admin-panel doesn't open.
it's not clear if you meant that it doesn't open automatically (as it should by default), or even manually.
is your linux a VPS? is it a docker container?

**Comment by Akai-Abd** [comment]
Yes It doesn't open automatically (as it should by default)

But if I open manually in browser it's working 
http://localhost/~/admin/

I am using on my pc Linux mint 22 Wilma

**Comment by rejetto** [comment]
can you please run `npx hfs@exp` and tell me if it fixes the problem?

**Comment by Akai-Abd** [comment]
No any fix

![hfs fire](https://github.com/user-attachments/assets/b3001506-b98f-4ddc-9cd0-b266c83d1072)


![nmp hsd@exp](https://github.com/user-attachments/assets/dc19dc7c-b649-47a5-b1d1-88e447083a82)

![hfs@exp](https://github.com/user-attachments/assets/25b28708-df4a-46f0-8326-a844e80b8c49)

![hfs@shre](https://github.com/user-attachments/assets/1ff4ec5d-c475-4b22-875e-807027789102)

![hfs@firefox](https://github.com/user-attachments/assets/af289469-b382-4767-8255-3720946a7ad0)

**Comment by rejetto** [comment]
i don't understand how that is possible.
how is your home folder configured in the VFS?

**Comment by Akai-Abd** [comment]
If we do manually edit configure config.yaml and do some changes.
Can we do this?

**Comment by rejetto** [comment]
i don't understand what you mean.
can you publish a screenshot of your Admin-panel > Shared-files ?
or paste here what's in your config.yaml (removing any sensible information)

**Comment by Akai-Abd** [comment]
@rejetto  Hii

Hfs 0.53.1 is working fine but that it doesn't open automatically (as it should by default)



![hfs@0 53 1](https://github.com/user-attachments/assets/67ccb5d2-f9dd-4a7d-a169-197239644ff8)


But if I open manually in browser it's working
http://localhost/~/admin/

![hfs@admin](https://github.com/user-attachments/assets/cb573444-6968-4a6e-8cc5-7e6359e6504c)



![hfs@shared](https://github.com/user-attachments/assets/76bc48cd-26b9-4a16-9341-e73d3fd47518)


config.yaml..........
```
version: 0.53.1
enable_plugins:
  - antibrute
  - download-counter
  - list-uploader
vfs:
  children:
    - source: /media/baba/Curcial/WordPress Development and Freelancing Course.zip
```







![hfs@portforwarding](https://github.com/user-attachments/assets/ba60676f-797f-43ae-bb5e-6db7774dec55)



Another one thing my ISP didnt provide static ip address for port forwarding so i can share file only my network, not all over Network, so mood cut OFF, 
I am appreciated As your hard work and afford , but i can use it its purely full benefits.

Thanks for support

**Comment by rejetto** [comment]
thanks for the additional information.
please, if you want to ask about port forwarding, open a different issue/discussion.
i still can't find an explanation for the errors you've found running hfs@exp. I tried on my ubuntu machine, and i can't see anything like that.
i will make an attempt installing linux mint in a VM, but without much hope.

can you make an attempt and run `npx hfs@beta` ?

**Comment by rejetto** [comment]
i can't run linux mint as my cpu is arm, and mint doesn't support it

**Comment by Akai-Abd** [comment]
@rejetto Hii
version: 0.54.0-rc9 beta

![hfs@Beta](https://github.com/user-attachments/assets/334e585a-fffd-41e9-9ab5-cacdf350f1b2)


![hfs@error](https://github.com/user-attachments/assets/77fcab0e-0cdd-4aac-91a2-79a13cc9467f)


![hfs@errorD](https://github.com/user-attachments/assets/327e41e7-7b22-412a-a08e-81e4d64c55d2)


![hfs@browser](https://github.com/user-attachments/assets/e7294e21-c5cd-49f2-a106-4c523402d99d)


Config.yaml......
```yaml
version: 0.54.0-rc9
enable_plugins:
  - antibrute
  - download-counter
  - list-uploader
vfs:
  children: []
  can_see: true
  can_read: true
  can_list:
    - baba
  can_upload:
    this:
      - baba
    children:
      - baba
  can_delete:
    this:
      - baba
    children:
      - baba
  can_archive: true
  source: /root
accounts:
  baba:
    admin: true
    ignore_limits: true
    srp: 27488716086045005488877264233683402412903047869680472254853060398685144970886984629264626418683031223806584436315589116684133588619955025388511226477707658236549986791076458132664603042201795487513535268220182820290320441602168191120021644409873756706912596806413675301583600685934967358463123076173791684507|14769368508882528778812987204304171022008645465919954044899204569320222124418274684242034876536344848381940103460942040980587491477504016973745213190162836387695096323334713987901392114796002330968600744528268923057759983464287193407991625624583446718285170924769433529994375081743116772101311111308017034396174090931973295773638864652107573249124046151492936152548295021073622795439053234124648043017729329399340429523796906234690932047873968547643553692973380375587665106905415668135135148299804901044499850714693520108210418012682508084872210435494739306371154494495035619488065551640029557839680969837382507159129
base_url: http://192.168.1.10
```
