### ISSUE TITLE
Windows 10, HFS 0.54.0 rc9: Copy & paste and also drag & drop results in "." as the filename

### ISSUE THREAD

**Issue by merlinuwe** [rejetto/hfs#782]
1. I select Platz_02
2. I try add -> from folder
3. the new folder is a subfolder of Platz_02
4. I try to drag & drop the folder to the house --> "." ist the name of the folder (without "")
5. I try to copy & paste the folder to the house --> "." ist the name of the folder (without "")

(Reproducable on Windows 10.)

![image](https://github.com/user-attachments/assets/f886d8a0-4609-412d-8e87-418d5cd6e2e9)

**Comment by merlinuwe** [comment]
Here is a interesting part, when I add some of these folders directly into the config.yaml

```
vfs:
  source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_99
  can_list: true
  can_see: true
  children:
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_01
      can_read:
        - "1"
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_02
      can_read:
        - "2"
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_21
      can_read:
        - "21"
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_27
      can_read:
        - "27"
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_98
      can_read:
        - "98"
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_99
      can_read:
        - "99"
    - source: C:\Users\xy\OneDrive - xxx\Dokumente\Desktop\HFS\R304\Platz_100
      can_read:
        - "100"
  can_archive: true
force_lang: de
base_url: http://192.168.178.21:1080/Platz_99
update_to_beta: true
server_code: |-
  exports.middleware = ctx => {
     if (ctx.ip === '192.168.178.21') return // skip 
     const n = ctx.path.match(/Platz_(\d+)/)?.[1]
     if (n && n !== '21' && ctx.ip !== '192.168.178.' + Number(n))
         ctx.status = 403
  }
```
And so does it look in "shared files":

![image](https://github.com/user-attachments/assets/014d6de4-a532-4e63-bee4-19e5200adb7f)

Seems to have a problem with "99".
