### ISSUE TITLE
account  Bugs

### ISSUE THREAD

**Issue by cszheng1** [rejetto/hfs#895]
**Screenshots**

The account is not displayed normally

![Image](https://github.com/user-attachments/assets/8d9503fe-0fee-41b9-b2b7-6d14b0b59dfc)

Click the account icon to enter and a black screen will appear

![Image](https://github.com/user-attachments/assets/bb80301b-baf4-417b-97b4-d246dcfc3ab1)

Who can upload, can't choose the account created

![Image](https://github.com/user-attachments/assets/d84b4152-f695-4751-b420-5dcf44cf4ffd)

**Environment (please complete the following information):**
 - OS: [ Windows Server ]

![Image](https://github.com/user-attachments/assets/1e2ca810-d313-4d02-ad72-eb1838015ba7)

 - HFS Version [ hfs-windows-x64-0.56.0-rc8]
 - Browser [chrome 133.0.6943.59]

**Comment by rejetto** [comment]
hi, i need to look at the data stored for accounts.
please go to admin-panel > options > config file > copy without passwords
and paste here in a message

**Comment by cszheng1** [comment]
> hi, i need to look at the data stored for accounts. please go to admin-panel > options > config file > copy without passwords and paste here in a message
```yaml
version: 0.56.0-rc8
vfs:
  children:
    - source: D:\Downloads\vlc-3.0.21-win32.exe
  can_upload:
    - null
force_lang: zh
auto_check_update: false
accounts:
  zcs:
    admin: true
    disable_password_change: true
```
