### ISSUE TITLE
0.56.0 option allow_net unexpected behavior

### ISSUE THREAD

**Issue by ro-dev** [rejetto/hfs#939]
I use next configuration

```
accounts:
  group.local:
    allow_net: localhost|192.168.*
  user.john
    belongs:
      - group.local
vfs:
  children:
    - source: PATH/TO/folder_1
      can_read:
        - user.john
    - source: PATH/TO/folder_2
      can_read:
        - group.local
```

When I log in as "user.john" from wide routable IP-address (via the Internet),
I have access to folder_1 & folder_2.

Expected result:
When I log in as 'user.john' from a wide routable IP address (via the Internet),
I would have access only to folder_1, but not to folder_2. However, when I log
in as 'user.john' from a local routable IP address (localhost|192.168.*), I
would have access to both folder_1 & folder_2.

For now, I have to use two accounts for this purpose, but if it works as
expected, one account will be enough for me.

Thank you for the great project!
