### ISSUE TITLE
Improve the behavior of the mask option

### ISSUE THREAD

**Issue by ro-dev** [rejetto/hfs#952]
Hello!
I use next configuration:

```
vfs:
  children:
    - source: PATH/TO/folder_1
    name: Music
    masks:
      "**.mp3|**.m4a|**.flac|**.webp|**.jpg|**.png":
        can_read: true
      "**.*":
        can_read: false
```

I just wanted to filter only files, but this configuration also filters folders. For example, this configuration filters out the sub-folder named `Music 2.0`. I managed to overcome this by adding the rule `Music 2.0: can_read: true` before the other mask rules. It's working, but I don't think it's the right way. I see a solution as dividing the single permission into two for files & folders.

It could look like this:

```
masks:
  "**":
    folders_can_read: true
  "**.mp3|**.m4a|**.flac|**.webp|**.jpg|**.png":
    files_can_read: true
  "**.*":
    files_can_read: false
```
